# Generated by Django 6.1.1 on 2026-10-01 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DealerReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dealer_id', models.IntegerField()),
                ('dealership', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=100)),
                ('purchase', models.BooleanField(default=False)),
                ('review', models.TextField()),
                ('purchase_date', models.CharField(max_length=20)),
                ('car_make', models.CharField(max_length=100)),
                ('car_model', models.CharField(max_length=100)),
                ('car_year', models.IntegerField()),
                ('sentiment', models.CharField(default='Positive', max_length=20)),
            ],
        ),
    ]
